### ISSUE TITLE
Filter simulation by the user in db_manage script

### ISSUE THREAD

**Issue by grzanka** [yaptide/app#1131]
Currently the `db_manage` script is listing all simulations of all users. I would like to have couple of more features:

- [x] add in printout username if simulations/tasks are printed for all users
- [x] add a cmdline parameter to filter simulations/tasks by username
- [x] add an option to delete certain simulation/tasks from a DB

**Comment by jagodek** [comment]
should deleting simulation cause deletion of related tasks?

**Comment by grzanka** [comment]
> should deleting simulation cause deletion of related tasks?

Yes

**Comment by grzanka** [comment]
Add few sentences in markdown documents as well

**Comment by jagodek** [comment]
If I'm to write about changed/added commands then all commands should be listed as well, because they're missing in docs?

**Comment by grzanka** [comment]
> If I'm to write about changed/added commands then all commands should be listed as well, because they're missing in docs?

You can mention all of them briefly.
