### ISSUE TITLE
Improve installation time for requirements

### ISSUE THREAD

**Issue by grzanka** [yaptide/app#115]
It seems that right now numpy is being compiled from sources which takes significant time.

**Comment by grzanka** [comment]
This can be fixed by switching from `alpine` to `slim` Docker version.

here is a skeleton of the main Dockerfile:

```
FROM python:3.9-slim
ARG SHIELDHIT_PATH
COPY $SHIELDHIT_PATH /usr/local/bin/
WORKDIR /usr/local/app

# install dependencies
COPY ./requirements.txt ./
RUN pip install -r requirements.txt

# copy project
COPY yaptide ./yaptide
```

**Comment by p1003** [comment]
Now it is over 20 times faster...
