### ISSUE TITLE
Provide example setup for shieldhit simulation

### ISSUE THREAD

**Issue by grzanka** [yaptide/app#151]
Change default config for detect.dat in converter, to mimic files from below:
https://github.com/DataMedSci/pymchelper/tree/master/docs/images_generation

Generate example json in frontend based on description from above

Run the simulation using backend, then inspect the files using convertmc to see if the result is the same as shown here:
https://datamedsci.github.io/pymchelper/image_converter.html

**Comment by p1003** [comment]
@grzanka consider closing this issue

**Comment by grzanka** [comment]
Will definitely be fixed in https://github.com/yaptide/converter/issues/62
