### ISSUE TITLE
Add timestamp needed to evaluate execution time on Celery

### ISSUE THREAD

**Issue by grzanka** [yaptide/app#203]
backend should return to UI full information: 
 - when job has started (date)
 - when job has finished (date)
 - how long was it working
 - how many parallel threads were used

**Comment by grzanka** [comment]
See https://github.com/yaptide/ui/issues/642

**Comment by p1003** [comment]
IMO working time can be calculated with start and finish time.

**Comment by grzanka** [comment]
> IMO working time can be calculated with start and finish time.

I agree, do you think UI is better place for performing that calculation ?

**Comment by p1003** [comment]
It doesn't makes sense to me, to calculate such things in backend because this data is `aggregated` while others are `raw`

**Comment by grzanka** [comment]
> It doesn't makes sense to me, to calculate such things in backend because this data is `aggregated` while others are `raw`

OK, we can try to do it in UI

**Comment by p1003** [comment]
@grzanka consider closing this issue

**Comment by grzanka** [comment]
Fixed in #204
