### ISSUE TITLE
design API which supports custom_submit via bash script

### ISSUE THREAD

**Issue by grzanka** [yaptide/app#242]
Dummy method which can be easily and quickly integrated with UI which simply print some stuff on screen and return dummy results.

The reason: we would like to test it mainly by using UI.

The plan:
 - [x] clean API (i.e. obsolete methods for Celery)
 - [x] get manually an example JSON result file
 - [x] implement a route which returns an example JSON result without even connecting to the PLGRID cluster
 - [x] think if we need anything related to authentication in the API
 - [x] think if we need anything related to the submission method (celery / slurm) in the API
 - [x] #263

This should be integrated with UI as soon as possible

**Comment by grzanka** [comment]
The plan:
 - [x] clean API (i.e. obsolete methods for Celery)
 - [x] get manually an example JSON result file
 - [x] implement a route which returns an example JSON result without even connecting to the PLGRID cluster
 - [x] think if we need anything related to authentication in the API
 - [x] think if we need anything related to the submission method (celery / slurm) in the API
 - [x] document the API here https://github.com/yaptide/yaptide/wiki/REST-API-Documentation

This should be integrated with UI as soon as possible

**Comment by grzanka** [comment]
A few words about monitoring. Currently the monitoring relies on measuring progress of a single job. This has to be extended to many jobs (also for Celery). There is a route which monitors current simulation state (i.e. `sh/status` for Celery). Currently it has an optional information about progress in form for example "5000 / 10000".

We are already having a multiple processes, i.e. 16 for Celery. For Slurm we suppose to have i.e. 400 parallel jobs.

The monitoring should return a collection of numbers, i.e. for Celery we should send to UI 16 numbers representing progress of each 16 jobs. For Slurm the same.

As for now you can implement a dummy method which generates dummy & fake progrees (i.e. += 1000 every 0.1 second) for Slurm endpoint. We can integrate that with UI without even submitting jobs which start SHIELD-HIT12A on a cluster.

**Comment by p1003** [comment]
The foreseen parameters for job submition:
- simulation data (like in celery: project json or input files)
- (optional) sbatch parameters: header and/or list of command line arguments
- (optional) simulation custom name
- (optional) simulator type - currently only shieldhit is supported

Result:
- job_id
- various error messages if some occur


The foreseen parameters for job status check:
- job_id

Result:
- job_status
- (if available) result of simulation
- various error messages if some occur
