### ISSUE TITLE
Think about versioning of TOPAS

### ISSUE THREAD

**Issue by grzanka** [yaptide/app#399]
TOPAS may be nicer than Fluka, it may print version using `--version`. But still we need to attach that information to S3 data

**Comment by grzanka** [comment]
Can you investigate if S3 at Cyfronet supports versioning of the files ?

**Comment by Bogdan2423** [comment]
Yes, apparently cyfronet S3 supports versioning:
![Przechwytywanie](https://github.com/yaptide/yaptide/assets/92746092/6a791077-9bab-42e0-9c14-933e2e158cf4)

**Comment by grzanka** [comment]
Then think of the procedure how to manage several TOPAS versions. 
First approach which comes to my mind:
 - single bucket which keeps all versions of TOPAS datafiles and binaries, inside we have:
 - an object with TOPAS Linux binary, precompiled for certain architecture, annotated with given version (i.e. 3.9)
 - for each of datafiles an object annotated with version of TOPAS to which it belongs. 
 
What do you think ?

Can we use some kind of tags for annotations ? Then when downloading the files we could go through all objects in bucket which have given tag (i.e. "3.8"). 

Can we assign multiple tags per object ?

Take in mind that it may be that the same datafile (i.e. G4RealSurface2.2.tar) belongs to multiple versions of TOPAS.

**Comment by Bogdan2423** [comment]
We can assign tags to each object. Tags are stored as key-value pairs. Each version of an object has its own tags. More about tags [here](https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-tagging.html)
We could use it for example like this:
![tags](https://github.com/yaptide/yaptide/assets/92746092/37ab681b-2a87-4e10-a9d7-a69e58f2c0ce)
Then we can get the tags using boto3 like this:
`s3_client.get_object_tagging(Bucket="gent-compressed", Key=s3_object.key, VersionId="versionid")["TagSet"]`

We can either keep the list of supported TOPAS versions as tag for each geant file (coded as string), or we can keep the names of required geant files as tags for TOPAS files. For now I'm not sure which way is better. 
We need to keep in mind that each object can have max 10 tags of length max 256 characters, so we can't for example keep the version ID of each required geant file as tags for TOPAS files.

**Comment by grzanka** [comment]
So you confirm that there could be multiple values for the same tag key ?

Can we attach different tags to different versions of the same file?

**Comment by Bogdan2423** [comment]
1. There can only be one tag with a certain key. The value of a tag is a string. To keep multiple values for one tag key (for example a list of TOPAS versions) we need to somehow code it as a string. (for example just separate the versions using commas, then, since we are using python, we can easily split it into a list of versions using split() method)
2. Yes, each version of the same file has its own set of tags.

**Comment by grzanka** [comment]
We have S3 tags
