### ISSUE TITLE
Estimate space for TOPAS blobs

### ISSUE THREAD

**Issue by grzanka** [yaptide/app#400]
Here datafiles are particluarly large. The question: how do we store datafiles: compressed or uncompressed. What is the difference in size for both options ?
What is faster: to download uncompressed version or to download compressed version and uncompress it ?

What is handy that datafiles are stored publicly.

Advanced use case. Some of the simulation require all the datasets, but some of them require only few percent of data. Does it make sense to ship all the datafiles if user may need only a fraction ? Maybe we should separate S3 data into 2 entities: binary exe + library and datafiles.

**Comment by Bogdan2423** [comment]
Topas files size: 152 MB
Compressed geant4 files: 1,52 GB
Uncompressed geant4 files: 1,78 GB
I dont't know if there is a way to download uncompressed geant datasets - on [geant website](https://geant4.web.cern.ch/download/11.1.1.html#datasets) I see only links to download them as .tar.gz archives.

As to the advanced use case - I in fact managed to run a simple simulation using only 2 geant datasets, which together are around 500 MB. The question is how to check which datasets will be required for a particular simulation

**Comment by grzanka** [comment]
> Topas files size: 152 MB Compressed geant4 files: 1,52 GB Uncompressed geant4 files: 1,78 GB I dont't know if there is a way to download uncompressed geant datasets - on [geant website](https://geant4.web.cern.ch/download/11.1.1.html#datasets) I see only links to download them as .tar.gz archives.

Can you estimate as well:
 - time needed to download compressed datafiles (assuming your Internet bandwith is not an issue)
 - time needed to decompress all those datafiles
 
> As to the advanced use case - I in fact managed to run a simple simulation using only 2 geant datasets, which together are around 500 MB. The question is how to check which datasets will be required for a particular simulation

That is a very good observation ! Selection of datafiles is based on "physics list" which user has choosen during simulation, its not so straightforward to figureout what is needed.

**Comment by Bogdan2423** [comment]
Download: around 2.5 minutes (bandwith around 200 Mbps)
Decompress: a bit over 50 seconds

**Comment by grzanka** [comment]
Another aspect to investigate:
 - put these compressed datafiles in S3, estimate time for download + decompression
 - put these uncompressed datafiles in S3, estimate time for download itself.
I am curious which combination of storage and compression is most time-efficient

**Comment by Bogdan2423** [comment]
Tested on Cyfronet S3 using WinSCP client:
Downloading uncompressed files (.tar): 5 min 10 s
Downloading compressed files (.tar.gz): 4 min 30 s

Including the decompress time of around 50 seconds, the slightly faster option, in this case, would be downloading uncompressed files. However, it will vary depending on bandwidth and decompression time. The download speed was around 6 MBps - if the bandwidth is less than that, the difference will increase in favor of compressed files.

**Comment by grzanka** [comment]
I am not sure how much reliable is WinSCP when handling S3 transfers.
Could you try the script from this branch:
https://github.com/yaptide/yaptide/pull/421/files
Most probably we would need to extend this script to handle TOPAS as well, excluding encryption (as TOPAS is open source).

Also - there is good summary of GUI and CLI clients for S3 here:
https://guide.s3p.cloud.cyfronet.pl/narzedzia_gui.html

I am also in favour of downloading uncompressed tar file.

**Comment by Bogdan2423** [comment]
I wrote a similar script just to test geant download:
```
s3_client = boto3.resource(
    "s3",
    aws_access_key_id=access_key,
    aws_secret_access_key=secret_key,
    endpoint_url=url
)

  start = time.time()
  bucket = s3_client.Bucket(bucket_name)
  for s3_object in bucket.objects.all():
      print("current time: ", time.time() - start, " seconds")
      print("downloading: ", s3_object.key)
      path, filename = os.path.split(s3_object.key)
      bucket.download_file(s3_object.key, filename)

  print()
  print("Downloaded in: ", time.time() - start, " seconds")
```

Results were interesting:
uncompressed: 83 s
compressed: 81 s
So now there was basically no difference in download times.

By the way, I tried two clients from the cyfronet guide earlier (S3 Browser and Cyberduck), but their free versions didn't allow for downloading multiple files at once

**Comment by grzanka** [comment]
Interesting: ~80 seconds using boto3 vs ~5 min using WinSCP ? 
I would go with uncompressed option. 

Is there anything else you would like to add or can we close this issue ?

**Comment by grzanka** [comment]
@Bogdan2423  Take a look as well at https://github.com/yaptide/yaptide/issues/399

**Comment by Bogdan2423** [comment]
> Interesting: ~80 seconds using boto3 vs ~5 min using WinSCP ? I would go with uncompressed option.
> 
> Is there anything else you would like to add or can we close this issue ?

 I think we can close this issue
