### ISSUE TITLE
Enviromental variables

### ISSUE THREAD

**Issue by grzanka** [yaptide/app#401]
For sure there are enviromental variables pointing to the datafiles. Note here what is needed.

**Comment by Bogdan2423** [comment]
Topas requires one env variable: TOPAS_G4_DATA_DIR. which contains location of geant datafiles. For example: `export TOPAS_G4_DATA_DIR=$HOME/G4Data`

**Comment by grzanka** [comment]
What about shared libraries (*.so) from TOPAS/Geant4 ? Lets assume that we compile TOPAS on one machine and have `topas` binary file there.

1. Compile TOPAS on your own computer (Linux!)
2. Create a new docker container based on debian:stable
3. Copy `topas` binary into that container (`docker cp`)
4. Download (`wget`) / copy (`docker cp`) Geant4 data files into container
5. This way we have a container which hase bare Linux OS and the only additional files is single topas binary executable and bunch of data files.
6. Copy (`docker cp`) single text file with TOPAS input file into container
7. Run interactive shell (bash) on docker container, set `TOPAS_G4_DATA_DIR` and try to run TOPAS executable on single config.

This way you should discover what else is needed to run TOPAS simulator, apart from topas executable and datafiles. Probably it is dynamically linked to tons of other libraries.

**Comment by Bogdan2423** [comment]
In fact, there are other libraries required. From topas installation guide:
_Debian:
Install the following:
apt install -y libexpat1-dev
apt install -y libgl1-mesa-dev
apt install -y libglu1-mesa-dev
apt install -y libxt-dev
apt install -y xorg-dev
apt install -y build-essential
apt install -y libharfbuzz-dev_

**Comment by grzanka** [comment]
Most probably many of these libraries are needed only to run TOPAS Qt GUI which we don't need at all.
Everything else we can put in [Dockerfile-worker](https://github.com/yaptide/yaptide/blob/master/Dockerfile-worker) 
We already have there gfotran which is needed to run SHIELD-HIT12A

**Comment by grzanka** [comment]
To proceed with this issue we need to integrate first download of TOPAS binaries an executable via S3. Then we could start adapting the dockerfiles

**Comment by grzanka** [comment]
Done in PR https://github.com/yaptide/yaptide/pull/650
