### ISSUE TITLE
reading output of TOPAS simulation

### ISSUE THREAD

**Issue by grzanka** [yaptide/app#409]
We need to:
- [x] #411
- [x] #412

**Comment by Bogdan2423** [comment]
created this issue on pymchelper repository: https://github.com/DataMedSci/pymchelper/issues/646

**Comment by grzanka** [comment]
Which pymhelper release has that feature? I think we currently have 2.5.1 in yaptide

**Comment by Bogdan2423** [comment]
This feature is in pymchelper 2.5.2
