### ISSUE TITLE
Missing method in proxy

### ISSUE THREAD

**Issue by hendzeld** [yaptide/app#482]
The current Nginx configuration does not allow us to access endpoint with PUT method:
https://github.com/yaptide/yaptide/blob/ae432b40527b5541927a1d090ce856169ce3f7f8/nginx.conf#L21

Currently, we have only one such endpoint in use (`/auth/register`):

https://github.com/yaptide/yaptide/blob/a392634fcf3c3e09409a853a5740a1303cdd1117/yaptide/static/openapi.yaml

Therefore this is a minor issue.

**Comment by grzanka** [comment]
@p1003 what is the status of `/auth/register` ?
