### ISSUE TITLE
Requested primaries and simulated primaries are not equal in COMPLETED task

### ISSUE THREAD

**Issue by Derstilon** [yaptide/app#484]
![image](https://github.com/yaptide/yaptide/assets/26445545/41875979-186d-46e9-9eb9-39bca169ac55)
Frontend handles it for now and logs an error, but the backend response must provide accurate info.

**Comment by grzanka** [comment]
The problem is known, logfile watcher doesn't send update on calculated primaries for fast simulations

I think we can fix it with rewriting celery to run single processes. There are more of the problems of this kind, see:
https://github.com/yaptide/yaptide/issues/467
