### ISSUE TITLE
Remove periodical calls to SLURM for job status checks

### ISSUE THREAD

**Issue by grzanka** [yaptide/app#529]
Needs #524 

- [x] clean openapi.yaml from outdated entries
- [x] unified job status query as GET endpoint under `/jobs` (instead of two `/jobs/batch` and `/jobs/direct`). This require easy change in UI: https://github.com/yaptide/ui/blob/975682f3a07c7dc642449a5e2eb9383475b0f38b/src/services/ShSimulatorService.tsx#L469C32-L469C32
- [x] new endpoint for "on-demand" queries of SLURM: `/jobs/batch` as GET

The plan is that all periodic calls for status updates (list of simulations, job progress etc) from UI should be realised on backend as queries from database. This should give performance improvement.

The queries to SLURM should be made only "on demand" (for example via dedicated button "get status" on a simulation).

In case the notification system (watcher.py) is broken and in the database we have no information at all, then all the tasks and simulations in such state should have a new state, called UNKNOWN. This may be implemented easily on creation of the objects in the DB, instead of creating the object in PENDING state, give them state UNKNOWN.

For Celery transition from UNKNOWN to PENDING happens when simulation will get job_id from Celery.
For SLURM this transition happens when we obtain job id from slurm. Here it may be time consuming as to get job id we need to call slurm via fabric/ssh. 
Simulations with UNKNOWN state will have empty list of tasks. This should be properly displayed in the UI.

When listing simulations we should list simulation with UNKNOWN state as well.

**Comment by p1003** [comment]
Following the merge of https://github.com/yaptide/yaptide/pull/586 consider closing this issue @grzanka

**Comment by grzanka** [comment]
@p1003 what about the "UNKNOWN" state as described here:

> In case the notification system (watcher.py) is broken and in the database we have no information at all, then all the tasks and simulations in such state should have a new state, called UNKNOWN. This may be implemented easily on creation of the objects in the DB, instead of creating the object in PENDING state, give them state UNKNOWN.
> 
> For Celery transition from UNKNOWN to PENDING happens when simulation will get job_id from Celery.
> For SLURM this transition happens when we obtain job id from slurm. Here it may be time consuming as to get job id we need to call slurm via fabric/ssh.
> Simulations with UNKNOWN state will have empty list of tasks. This should be properly displayed in the UI.
> 
> When listing simulations we should list simulation with UNKNOWN state as well.
