### ISSUE TITLE
Improve API documentation

### ISSUE THREAD

**Issue by grzanka** [yaptide/app#624]
As for now the documentation is nicely rendered here:
https://yaptide.github.io/yaptide/swagger/

- [x] GET /
It says that it will check if server is alive. OK, but what this will return if server is dead ?
![image](https://github.com/yaptide/yaptide/assets/7374733/b68a15bf-0f65-4041-83de-cd97a63a59e9)

- [x] PUT /auth/register
Does it really reply with hello world ?
What happens if we try to register username with already existing name ?
![image](https://github.com/yaptide/yaptide/assets/7374733/396785a7-4b39-42dd-8a9d-6e2d7bd4d4a5)

- [ ] POST /auth/login
Does it really reply with hello world ?
Explain units of access_exp and refresh_exp. What is included in message payload ?

- [ ] GET /auth/status
What is the purpose of this endpoint ? It says "to retrieve logged in user information". What kind of user information ?

**Comment by p1003** [comment]
> GET /
It says that it will check if server is alive. OK, but what this will return if server is dead ?

It won't return anything because server is dead

**Comment by p1003** [comment]
>  GET /auth/status
What is the purpose of this endpoint ? It says "to retrieve logged in user information". What kind of user information ?

For now it only returns the username, because we didn't come accross with any need of more information here. You can see every information in the example response for code 200.

**Comment by grzanka** [comment]
> > GET /auth/status
> > What is the purpose of this endpoint ? It says "to retrieve logged in user information". What kind of user information ?
> 
> For now it only returns the username, because we didn't come accross with any need of more information here. You can see every information in the example response for code 200.

Then the documentation should be explicit, like:

"Retrieve information about logged in user (i.e. username)".

When request was successful (code 200) then we see also "message". Documentation doesn't say whats inside.
