### ISSUE TITLE
Prevent pushing not empty .env file

### ISSUE THREAD

**Issue by hendzeld** [yaptide/app#667]
Previously, one of the contributors pushed `.env` file with credentials.

To prevent this from happening, we could:
- Add a pre-commit hook. It will abort the push or ask the user (if it is possible in hooks) if he really wants to push `.env` file.
- remove and .env file
- other solution

**Comment by grzanka** [comment]
In this PR https://github.com/yaptide/yaptide/pull/664/files I've added pre-commit configuration. Maybe this could help ?

**Comment by grzanka** [comment]
Check https://github.com/pre-commit/pre-commit-hooks/tree/main/pre_commit_hooks
