### ISSUE TITLE
Error while executing command

### ISSUE THREAD

**Issue by lequ0n** [yaptide/app#746]
Page Overview

I followed steps described there: https://yaptide.github.io/deploy/
However when executing command below I'm getting an 'error'

![image](https://github.com/yaptide/deploy/assets/100755599/a9de27e9-68ea-4b8c-8861-dbf9ad0fab7a)

There is an additional carriage return character after word python.
I haven't edited any file.

I'm working on windows10
Using keyword `python` seems to solve the problem, but I assume it's not the desired solution

![image](https://github.com/yaptide/deploy/assets/100755599/39db1739-3d7b-483f-8daf-e1edf0111fb1)

**Comment by grzanka** [comment]
I think we need to replace `\r\n` with `\n` in `db_manage.py` file. We can do it in similar way as in https://github.com/yaptide/yaptide/blob/aa74c9d481be955a5eb7273acaa275da8c516661/Dockerfile-worker#L38
