### ISSUE TITLE
Update „Running the app” section, so it is more descriptive for developers

### ISSUE THREAD

**Issue by MatoKnap** [yaptide/app#868]
Here are proposed changes:
- [x] Use more descriptive names for options
- [x] #869
- [x] Use local environment variables instead of exporting them
- [x] Add options necessary for debugging

This draft is not complete because app does not create tables in the database.

## Running the app

1. Get the redis
- If you already use it just start it on port `6379`
- If not good solution would comes with help of docker, run the following commands:
	- `$ docker run --detach --publish 6379:6379 --name yaptide_redis redis:6-alpine`
	- To remove this container use: `$ docker rm -f yaptide_redis`

2. Run Celery with `$ CELERY_BROKER_URL=redis://127.0.0.1:6379/0 CELERY_RESULT_BACKEND=redis://127.0.0.1:6379/0 BACKEND_INTERNAL_URL=http://127.0.0.1:6000 celery --app yaptide.celery.worker worker --events --loglevel=info --pool eventlet`

    - You can reuse the same terminal, as for redis, as docker sends redis process to the background

3. Run the app: `$ FLASK_APP=yaptide.application FLASK_DEBUG=1 FLASK_SQLALCHEMY_DATABASE_URI=sqlite:///test.db flask run`

    - By default the app will re-create the database with each run, dropping it in the process.
    - To persist the database between runs this `with app.app_context(): models.create_models()` in yaptide/application.py inside the `create_app` factory.

**Comment by grzanka** [comment]
@MatoKnap do you think that PR #879 will close this issue ?

**Comment by grzanka** [comment]
Seems fixed now
