### ISSUE TITLE
Avoid blocking calls to long method (SH12A simulation)

### ISSUE THREAD

**Issue by grzanka** [yaptide/app#91]
Right now call to `/sh/demo` is blocking operation.
When using `curl localhost:5000/sh/demo` to start simulation curl is waiting until simulation is finished.

This is not the desired way. The simulation tasks should be asynchronous.

Take a look here for inspiration how to use Celery for task management:
https://testdriven.io/blog/flask-and-celery/

**Comment by p1003** [comment]
One more article about it
https://blog.miguelgrinberg.com/post/using-celery-with-flask
